### ISSUE TITLE
policy checkpoint and the environments

### ISSUE THREAD

**Issue by Damax18** [Embracing/Active3DPose#2]
Thanks for your great work!!!
(1) Can you provide new checkpoints download link to evaluate your agent?
(2) What's your training environment setting for this algorithm, just like how long does this training process become converged on which gpu and cpu settings?
(3) What's more, all the four download binary environments are ten women in the blank environments, it seems like that other three environments (gym, street, grass) didn't  upload yet

```
https://disk.pku.edu.cn/#/link/56F3EA16170527EABFA1F0497B66D1F2
Valid Until: 2023-05-05 23:59
```
You can find the model checkpoints of the control policies for 3 to 5 cams in the zip file. I did an evaluation on the Blank Environment with each model myself to save you the troubles. You can view the evaluated results with our PyQT visualizer.

_Originally posted by @mickelliu in https://github.com/Embracing/Active3DPose/issues/1#issuecomment-1498688331_

**Comment by mickelliu** [comment]
Hi @Damax18, thanks for your interest in our work.

(1) `https://disk.pku.edu.cn:443/link/21C2E2F8AFC20EEF69262F40A7D8432F
Valid Until: 2023-06-08 23:59`

(2) Should be the same as the default settings in the training code. Check out this short documentation `https://github.com/Embracing/Active3DPose/blob/main/docs/train.md`, the GPU and CPU settings should be in there. 

> just like how long does this training process become converged on which gpu and cpu settings?

This would depend on a few things: your systems spec, TensorRT-complied perception models and the number of humans or cameras in the simulation environment.
From our experiences, to simulate 500k environment steps (sampling+training) 2-cameras experiment costs 6-8 hours and 5-cameras experiment costs ~16 hours. The convergence on the MPJPE could happen much earlier than 500k, we train to 500k to tune down the entropy of the control policies (so it appears so stable). Please note that our system's spec isn't spectacular in any way.

(3) Could you please double-check this? The file on Google Drive is 3.4 gibs, so it should contain everything (with each Linux binary being 300~800 MBs). How did you switch between the environments? Please elaborate.

**Comment by Damax18** [comment]
Thanks for your reply!
I download the binary.zip file and the file is 3.44GB. Then I unzip it on Unbuntu platform, and double-click the file _binary/**blank**/AnimalParsing/Binaries/Linux/AnimalParsing_ (about 106MB ), ten women in an blank environment can be launched successfully. 
But other binary files (such as _binary/**building**/AnimalParsing/Binaries/Linux/AnimalParsing_, _binary/**grass**/AnimalParsing/Binaries/Linux/AnimalParsing_,
_binary/**gym**/AnimalParsing/Binaries/Linux/AnimalParsing_) are all 106GB, and the content is all the same(ten women in an blank environment) after I double-click these binary files.

**Comment by mickelliu** [comment]
These binary files have the same size, the differences being the assets `AnimalParsing\Content\Paks`. The reason why you were seeing ten women in the blank environments was probably that the assets weren't loaded properly.

Try running the shell script `AnimalParsing.sh` to see if it can run the binary with loaded assets. But it likely won't work because we use UnrealCV python commands in our code to load the assets manually (such as in `env.reset()`). These binaries files aren't the ”all-in-one" binary that you are likely seeing from the AirSim project.

For example, here we are loading the mesh assets for the simulated humans:

https://github.com/Embracing/Active3DPose/blob/05888366b50ad2120597b489621f1d9dbd78a5ac/activepose/envs/internal/human_control_v13.py#L156-L183

You can check out the UnrealCV documentation for more details.

So if you wanna check out different environments, it is best to run the training code, evaluate the policy, and check the video renderings in the visualizer.

**Comment by Damax18** [comment]
Thanks， I evaluate the policy, and different environments are rendering successfully!
By the way, could you provide some tips about how to control people's actions (eg. run, walk randomly, walk straight, walking speed)、change clothes、change skeletons when you are building the environment in UE4?

**Comment by Embracing** [comment]
We use built-in blueprint functions to control people's actions. E.g. Here is a tutorial on how to set up character movement. [https://docs.unrealengine.com/4.27/en-US/InteractiveExperiences/HowTo/CharacterMovement/](url). You can control whether a character is running or walking by setting a speed parameter and adjusting it from Python via Unrealcv.
